# docker-compose.yml
version: "3"
services:
  webserver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: php_img
    ports:
      - 8000:80
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html:delegated
    entrypoint:
      - ./docker/entrypoint.sh
  mysql:
    image: mariadb:10.2
    container_name: mariadb-server-10-2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=.sweetpwd.
      - MYSQL_DATABASE=kaartenmaker
      - MYSQL_USER=kaartenmaker
      - MYSQL_PASSWORD=secret
    ports:
      - "13306:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mariadb-server-10-2
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
    volumes:
      - /sessions
