<?php
set_time_limit(0);

$a_kaarten = array(
	'01h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'02g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'03a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'03c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'03d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'03g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'04f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'05a-griend'		=> array('origin' => array(x,y), 'size' => array(w,h)),
	'05a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'05f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'05g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'05h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'06a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'06b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'06c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'06d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'06e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'06f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'06g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'06h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'07a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'07b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'07c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'07d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'07e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'07f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'07g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'07h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'08c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'09b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'09h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'10b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'10e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'10f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'10g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'10h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'11a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'11b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'11c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'11d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'11e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'11f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'11g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'11h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'12a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'12b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'12c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'12d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'12e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'12f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'12g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'12h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'13a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'13c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'14b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'14d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'14e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'14g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'14h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'15b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'15e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'15f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'15h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'16a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'16b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'16c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'16d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'16e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'16f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'16g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'16h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'17a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'17b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'17c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'17d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'17e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'17f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'17g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'17h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'18a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'19a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'19b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'19c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'19d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'19e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'19f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'19g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'19h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'20a-de-kreupel'	=> array('origin' => array(x,y), 'size' => array(w,h)),
	'20a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'20b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'20f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'20g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'20h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'21a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'21b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'21c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'21d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'21e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'21f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'21g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'21h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'22a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'22b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'22c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'22d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'22e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'22g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'24h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'25a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'25b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'25c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'25d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'25e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'25f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'25g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'25h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'26a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'26b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'26c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'26d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'26e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'26f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'26g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'26h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'27a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'27b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'27c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'27d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'27e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'27f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'27g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'27h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'28a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'28b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'28c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'28d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'28e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'28f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'28g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'28h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'29a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'29c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'30d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'30e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'30f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'30g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'30h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'31a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'31b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'31c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'31d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'31e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'31f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'31g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'31h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'32a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'32b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'32c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'32d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'32e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'32f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'32g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'32h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'33a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'33b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'33c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'33d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'33e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'33f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'33g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'33h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'34a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'34b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'34c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'34d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'34e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'34f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'34g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'37a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'37b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'37c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'37d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'37e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'37f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'37g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'37h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'38a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'38b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'38c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'38d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'38e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'38f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'38g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'38h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'39a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'39b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'39c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'39d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'39e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'39f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'39g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'39h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'40a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'40b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'40c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'40d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'40e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'40f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'40g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'41a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'41b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'41c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'41e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'43a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'43b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'43c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'43d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'43e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'43f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'43g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'43h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'44a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'44b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'44c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'44d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'44e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'44f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'44g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'44h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'45a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'45b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'45c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'45d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'45e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'45f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'45g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'45h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'46a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'46b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'46c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'46d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'49a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'49b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'49c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'49d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'49e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'49f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'49g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'50a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'50b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'50e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'50f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'50g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'50h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'51a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'51b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'51c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'51d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'51e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'51f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'51g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'51h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'52a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'52b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'52c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'52d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'52e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'52g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'55a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'57a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'57b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'57e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'57f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'57h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'58a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'58b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'58c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'58d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'58e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'58g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'64f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'64g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'64h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'65a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'65b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'65c'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'65d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'65e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'65f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'65g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'65h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'67a'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'67b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'67e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'67f'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'67g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'67h'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'68b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'68d'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'68e'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'68g'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'69b'				=> array('origin' => array(x,y), 'size' => array(w,h)),
	'69e'				=> array('origin' => array(x,y), 'size' => array(w,h))
);



$a_kaarten = array(
	'01W'	=>	array('origin' => array(140, 600)),
	'01O'	=>	array('origin' => array(160, 600)),
	'02W'	=>	array('origin' => array(180, 600)),
	'02O'	=>	array('origin' => array(200, 600)),
	'03W'	=>	array('origin' => array(220, 600)),
	'03O'	=>	array('origin' => array(240, 600)),
	
	'04'	=>	array('origin' => array(114, 575), 'size' => array(26, 25)),
	'05W'	=>	array('origin' => array(140, 575)),
	'05O'	=>	array('origin' => array(160, 575)),
	'06W'	=>	array('origin' => array(180, 575)),
	'06O'	=>	array('origin' => array(200, 575)),
	'07W'	=>	array('origin' => array(220, 575)),
	'07O'	=>	array('origin' => array(240, 575)),
	'08'	=>	array('origin' => array(260, 575)),
	
	'09'	=>	array('origin' => array(100, 550), 'size' => array(30, 25)),
	'10W'	=>	array('origin' => array(130, 550), 'size' => array(30, 25)),
	'10O'	=>	array('origin' => array(160, 550)),
	'11W'	=>	array('origin' => array(180, 550)),
	'11O'	=>	array('origin' => array(200, 550)),
	'12W'	=>	array('origin' => array(220, 550)),
	'12O'	=>	array('origin' => array(240, 550)),
	'13'	=>	array('origin' => array(260, 550)),
	
	'14W'	=>	array('origin' => array(100, 525)),
	'14O'	=>	array('origin' => array(120, 525), 'size' => array(30, 25)),
	'15'	=>	array('origin' => array(150, 525), 'size' => array(30, 25)),
	'16W'	=>	array('origin' => array(180, 525)),
	'16O'	=>	array('origin' => array(200, 525)),
	'17W'	=>	array('origin' => array(220, 525)),
	'17O'	=>	array('origin' => array(240, 525)),
	'18'	=>	array('origin' => array(260, 525)),
	
	'19W'	=>	array('origin' => array(100, 500)),
	'19O'	=>	array('origin' => array(120, 500), 'size' => array(30, 25)),
	'20'	=>	array('origin' => array(150, 500), 'size' => array(30, 25)),
	'21W'	=>	array('origin' => array(180, 500)),
	'21O'	=>	array('origin' => array(200, 500)),
	'22W'	=>	array('origin' => array(220, 500)),
	'22O'	=>	array('origin' => array(240, 500), 'size' => array(30, 25)),
	
	'25W'	=>	array('origin' => array( 88, 475), 'size' => array(32, 25)),
	'25O'	=>	array('origin' => array(120, 475)),
	'26W'	=>	array('origin' => array(140, 475)),
	'26O'	=>	array('origin' => array(160, 475)),
	'27W'	=>	array('origin' => array(180, 475)),
	'27O'	=>	array('origin' => array(200, 475)),
	'28W'	=>	array('origin' => array(220, 475)),
	'28O'	=>	array('origin' => array(240, 475), 'size' => array(30, 25)),
	
	'30'	=>	array('origin' => array( 68, 450), 'size' => array(32, 25)),
	'31W'	=>	array('origin' => array(100, 450)),
	'31O'	=>	array('origin' => array(120, 450)),
	'32W'	=>	array('origin' => array(140, 450)),
	'32O'	=>	array('origin' => array(160, 450)),
	'33W'	=>	array('origin' => array(180, 450)),
	'33O'	=>	array('origin' => array(200, 450)),
	'34W'	=>	array('origin' => array(220, 450)),
	'34O'	=>	array('origin' => array(240, 450), 'size' => array(30, 25)),
	
	'37W'	=>	array('origin' => array( 54, 425), 'size' => array(26, 25)),
	'37O'	=>	array('origin' => array( 80, 425)),
	'38W'	=>	array('origin' => array(100, 425)),
	'38O'	=>	array('origin' => array(120, 425)),
	'39W'	=>	array('origin' => array(140, 425)),
	'39O'	=>	array('origin' => array(160, 425)),
	'40W'	=>	array('origin' => array(180, 425)),
	'40O'	=>	array('origin' => array(200, 425)),
	'41W'	=>	array('origin' => array(220, 425)),
	'41O'	=>	array('origin' => array(240, 425)),
	
	'43W'	=>	array('origin' => array( 60, 400)),
	'43O'	=>	array('origin' => array( 80, 400)),
	'44W'	=>	array('origin' => array(100, 400)),
	'44O'	=>	array('origin' => array(120, 400)),
	'45W'	=>	array('origin' => array(140, 400)),
	'45O'	=>	array('origin' => array(160, 400)),
	'46'	=>	array('origin' => array(180, 400), 'size' => array(27, 25)), // Actually this is 26 + a bit...
	
	'49W'	=>	array('origin' => array( 60, 375)),
	'49O'	=>	array('origin' => array( 80, 374), 'size' => array(20, 26)), // There's an extra bit at the bottom
	'50W'	=>	array('origin' => array(100, 375)),
	'50O'	=>	array('origin' => array(120, 375)),
	'51W'	=>	array('origin' => array(140, 375)),
	'51O'	=>	array('origin' => array(160, 375)),
	'52W'	=>	array('origin' => array(180, 375)),
	'52O'	=>	array('origin' => array(200, 375)),
	
	'55'	=>	array('origin' => array( 60, 350)),
	'57W'	=>	array('origin' => array(127, 350), 'size' => array(33, 25)),
	'57O'	=>	array('origin' => array(160, 350)),
	'58W'	=>	array('origin' => array(180, 350)),
	'58O'	=>	array('origin' => array(200, 350)),
	
	'64'	=>	array('origin' => array( 34, 405), 'size' => array(26, 25)),
	'65W'	=>	array('origin' => array( 13, 380), 'size' => array(27, 25)),
	'65O'	=>	array('origin' => array( 40, 380)),
	'67W'	=>	array('origin' => array( 13, 355), 'size' => array(27, 25)),
	'67O'	=>	array('origin' => array( 40, 355)),

	'68W'	=>	array('origin' => array(170, 325)),
	'68O'	=>	array('origin' => array(190, 325)),
	'69W'	=>	array('origin' => array(170, 300)),
	'69O'	=>	array('origin' => array(190, 300))

);

define('x', 0);
define('y', 1);

foreach($a_kaarten as $s_key => $a_kaartInfo) {
	if(isset($a_kaartInfo['size'])) {
		$h = $a_kaartInfo['size'][y];
		$w = $a_kaartInfo['size'][x];
	}
	else {
		$h = 25;
		$w = 20;
	}
	
	$a_matches = glob('kaarten_origineel/TOP50raster_GEOTIFF_november_2014/TOP50raster_GEOTIFF_november_2014/TOP50raster_GEOTIFF/TOP50raster-'.$s_key.'*.tif');
	$s_filename = $a_matches[0];
	
	// De kadaster kaarten zorgen voor zwarte tiles als we ze in 1 keer converten naar tiles. Daarom doen we het in 2 keer.
	exec('convert '.$s_filename.' kaart/kad50/origineel.png');
	exec('convert kaart/kad50/origineel.png -crop 200x200 +repage kaart/kad50/crop_%d.png');
	
	$X = $a_kaartInfo['origin'][x];
	$Y = $a_kaartInfo['origin'][y];
	
	for($i=0;$i<$h*$w;$i++) {
		$x = $X+$i%$w;
		$y = $Y+($h-ceil(($i+1)/$w));
		
		rename('kaart/kad50/crop_'.$i.'.png', 'kaart/kad50/'.$x.'-'.$y.'.png');
	}
}

unlink('kaart/kad50/origineel.png');
